# Generated by Django 5.2.9 on 2025-12-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Käyttäjät',
            fields=[
                ('käyttäjä_id', models.AutoField(primary_key=True, serialize=False)),
                ('käyttäjätunnus', models.CharField(max_length=50, unique=True)),
                ('salasana', models.CharField(max_length=128)),
                ('sähköposti', models.EmailField(max_length=254, unique=True)),
                ('luontiaika', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('ean_koodi', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('nimi', models.CharField(max_length=100)),
                ('kuva', models.CharField(blank=True, max_length=200)),
                ('valmistaja', models.CharField(blank=True, max_length=100)),
                ('kategoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Varastot',
            fields=[
                ('varasto_id', models.AutoField(primary_key=True, serialize=False)),
                ('sijainti', models.CharField(max_length=100)),
                ('määrä', models.IntegerField()),
                ('ostopäivä', models.DateTimeField()),
                ('viimeinen_käyttöpäivä', models.DateTimeField(auto_now=True)),
                ('ean_koodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapp.tuote')),
                ('käyttäjä_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapp.käyttäjät')),
            ],
        ),
    ]
