# Generated by Django 5.2.9 on 2025-12-18 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varastot',
            name='käyttäjä_id',
        ),
        migrations.AddField(
            model_name='varastot',
            name='kayttaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='varastot',
            name='ostopäivä',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='varastot',
            name='viimeinen_käyttöpäivä',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Käyttäjät',
        ),
    ]
