# Generated by Django 5.2.9 on 2025-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0002_remove_varastot_käyttäjä_id_varastot_kayttaja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='kategoria',
        ),
        migrations.RemoveField(
            model_name='tuote',
            name='valmistaja',
        ),
        migrations.AlterField(
            model_name='varastot',
            name='sijainti',
            field=models.CharField(choices=[('jääkaappi', 'Jääkaappi'), ('pakastin', 'Pakastin'), ('kuivakaappi', 'Kuivakaappi')], default='kuivakaappi', max_length=100),
        ),
    ]
